### ISSUE TITLE
Github release possible ? 

### ISSUE THREAD

**Issue by qbouvet** [shvchk/dolphin-squashfs-mount#1]
Hi, I'd like to create an AUR package for your extension. It allows arch linux users to easily it direcly via their package manager instead of the KDE store.

For technical reasons I find it slightly cleaner to write the package against a git release rather than picking the current latest commit number. Could you consider creating a git release ? 

Best regards,

Quentin

**Comment by shvchk** [comment]
Done :wink:

**Comment by qbouvet** [comment]
Amazing, thanks for the quick reaction !
