### ISSUE TITLE
KDE service menu path changed

### ISSUE THREAD

**Issue by ghost** [shvchk/dolphin-squashfs-mount#3]
Hey, 

FYI, the path for KDE service menu files changed. It appears to be no longer `~/.local/share/kservices5/ServiceMenus`, but instead `~/.local/share/kio/servicemenus` or `/usr/share/kio/servicemenus`. See [1].

The installation section of your readme still lists the old path, you might want to change it. 

Also, thanks for the work :)

----
[1] https://develop.kde.org/docs/apps/dolphin/service-menus/

**Comment by shvchk** [comment]
Thank you, will update soon :heart:
